In [1]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['IMDB_Top250Engmovies2_OMDB_Detailed.csv'].decode('utf-8')))

Saving IMDB_Top250Engmovies2_OMDB_Detailed.csv to IMDB_Top250Engmovies2_OMDB_Detailed.csv


In [2]:
df.head()

Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  ... tomatoConsensus  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...  ...             NaN   
1  Marlon Brando, Al Pacino, James Caan, Richard ...  ...             NaN   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...  ...             NaN   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...  ...             NaN   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....  ...             NaN   

  tomatoUserMeter tomatoUserRating tomatoUserReviews  \
0             NaN              NaN               NaN   
1             NaN              NaN               NaN   
2             NaN              NaN               NaN   
3             NaN              NaN               NaN   
4             NaN              NaN               NaN   

                                           tomatoURL          DVD  \
0  http://www.rottentomatoes.com/m/shawshank_rede...  27 Jan 1998   
1         http://www.rottentomatoes.com/m/godfather/  09 Oct 2001   
2  http://www.rottentomatoes.com/m/godfather_part...  24 May 2005   
3   http://www.rottentomatoes.com/m/the_dark_knight/  09 Dec 2008   
4  http://www.rottentomatoes.com/m/1000013-12_ang...  06 Mar 2001   

      BoxOffice                       Production  \
0           NaN                Columbia Pictures   
1           NaN               Paramount Pictures   
2           NaN               Paramount Pictures   
3  $533,316,061  Warner Bros. Pictures/Legendary   
4           NaN             Criterion Collection   

                                             Website Response  
0                                                NaN     True  
1                        http://www.thegodfather.com     True  
2                       http://www.thegodfather.com/     True  
3               http://thedarkknight.warnerbros.com/     True  
4  http://www.criterion.com/films/27871-12-angry-men     True  

[5 rows x 38 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         250 non-null    int64  
 1   Title              250 non-null    object 
 2   Year               250 non-null    int64  
 3   Rated              250 non-null    object 
 4   Released           248 non-null    object 
 5   Runtime            250 non-null    object 
 6   Genre              250 non-null    object 
 7   Director           250 non-null    object 
 8   Writer             249 non-null    object 
 9   Actors             250 non-null    object 
 10  Plot               250 non-null    object 
 11  Language           250 non-null    object 
 12  Country            250 non-null    object 
 13  Awards             245 non-null    object 
 14  Poster             250 non-null    object 
 15  Ratings.Source     250 non-null    object 
 16  Ratings.Value      250 non

In [6]:
df.isnull().sum()

Unnamed: 0             0
Title                  0
Year                   0
Rated                  0
Released               2
Runtime                0
Genre                  0
Director               0
Writer                 1
Actors                 0
Plot                   0
Language               0
Country                0
Awards                 5
Poster                 0
Ratings.Source         0
Ratings.Value          0
Metascore             73
imdbRating             0
imdbVotes              0
imdbID                 0
Type                   0
tomatoMeter          250
tomatoImage          250
tomatoRating         250
tomatoReviews        250
tomatoFresh          250
tomatoRotten         250
tomatoConsensus      250
tomatoUserMeter      250
tomatoUserRating     250
tomatoUserReviews    250
tomatoURL              0
DVD                    3
BoxOffice            175
Production             0
Website              119
Response               0
dtype: int64

In [7]:
df['Plot'][0]


'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.'

In [9]:
import pandas as pd
import numpy as np
import re
import nltk
pd.set_option('display.max_columns', None)

In [ ]:
## Data Preprocessing

In [10]:

df['clean_plot'] = df['Plot'].str.lower()  ## Converted the sentence into the lower Case String
df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('[^a-zA-Z]', ' ', x))  ## Removing the additional symbols from the string
df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('\s+', ' ', x))  # Removing the extra spaces.


In [11]:
df['clean_plot']

0      two imprisoned men bond over a number of years...
1      the aging patriarch of an organized crime dyna...
2      the early life and career of vito corleone in ...
3      when the menace known as the joker emerges fro...
4      a jury holdout attempts to prevent a miscarria...
                             ...                        
245    the desperate life of a chronic alcoholic is f...
246    a something supervising staff member of a resi...
247    a newspaper editor uses every trick in the boo...
248    an old man makes a long journey by lawn mover ...
249    a mumbai teen reflects on his upbringing in th...
Name: clean_plot, Length: 250, dtype: object

In [ ]:
## Craeting the tokenization for the sentence

In [15]:
import nltk
nltk.download('punkt')  ## NLTK requires some data files for tokenization

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [16]:
df['clean_plot'].fillna('', inplace=True)  ## fillna method is used to handle missing values.

# Tokenize the 'clean_plot' column
df['clean_plot'] = df['clean_plot'].apply(lambda x: nltk.word_tokenize(x))

# Display the tokenized 'clean_plot' column
print(df['clean_plot'])

0      [two, imprisoned, men, bond, over, a, number, ...
1      [the, aging, patriarch, of, an, organized, cri...
2      [the, early, life, and, career, of, vito, corl...
3      [when, the, menace, known, as, the, joker, eme...
4      [a, jury, holdout, attempts, to, prevent, a, m...
                             ...                        
245    [the, desperate, life, of, a, chronic, alcohol...
246    [a, something, supervising, staff, member, of,...
247    [a, newspaper, editor, uses, every, trick, in,...
248    [an, old, man, makes, a, long, journey, by, la...
249    [a, mumbai, teen, reflects, on, his, upbringin...
Name: clean_plot, Length: 250, dtype: object


In [20]:
import nltk
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
stop_words = set(nltk.corpus.stopwords.words('english'))

# Tokenize and filter words
plot = []
for sentence in df['clean_plot']:
    temp = []
    for word in sentence:
        if word not in stop_words and len(word) >= 3:
            temp.append(word)
    plot.append(temp)

In [23]:
df['clean_plot'] = plot


In [24]:
df['clean_plot']


0      [two, imprisoned, men, bond, number, years, fi...
1      [aging, patriarch, organized, crime, dynasty, ...
2      [early, life, career, vito, corleone, new, yor...
3      [menace, known, joker, emerges, mysterious, pa...
4      [jury, holdout, attempts, prevent, miscarriage...
                             ...                        
245    [desperate, life, chronic, alcoholic, followed...
246    [something, supervising, staff, member, reside...
247    [newspaper, editor, uses, every, trick, book, ...
248    [old, man, makes, long, journey, lawn, mover, ...
249    [mumbai, teen, reflects, upbringing, slums, ac...
Name: clean_plot, Length: 250, dtype: object

In [28]:
df['Genre'] = df['Genre'].apply(lambda x: x.split(',') if isinstance(x, str) else x)  ##takes each element (a string) in the 'Genre' column and splits it into a list of values using a comma , as the delimiter

df['Actors'] = df['Actors'].apply(lambda x: x.split(',')[:4] if isinstance(x, str) else x) ## This operation is used to limit the number of actors to the top four
df['Director'] = df['Director'].apply(lambda x: x.split(',') if isinstance(x, str) else x)

In [29]:
df['Actors'][0]


['Tim Robbins', ' Morgan Freeman', ' Bob Gunton', ' William Sadler']

In [ ]:
## Created a new function and performed data cleaning

In [31]:
def clean(sentence):
    temp = []
    for word in sentence:
        temp.append(word.lower().replace(' ', ''))  ## Converts word to lowercase and then removed the extra spaces
    return temp

In [33]:
df['Genre'] = [clean(x) for x in df['Genre']]
df['Actors'] = [clean(x) for x in df['Actors']]
df['Director'] = [clean(x) for x in df['Director']]

In [36]:
df['Actors'][0]


['timrobbins', 'morganfreeman', 'bobgunton', 'williamsadler']

In [ ]:
## created a new list l by concatenating the values from specific columns in the DataFrame

In [35]:
columns = ['clean_plot', 'Genre', 'Actors', 'Director']
l = []
for i in range(len(df)):
    words = ''
    for col in columns:
        words += ' '.join(df[col][i]) + ' '
    l.append(words)
l

['two imprisoned men bond number years finding solace eventual redemption acts common decency crime drama timrobbins morganfreeman bobgunton williamsadler frankdarabont ',
 'aging patriarch organized crime dynasty transfers control clandestine empire reluctant son crime drama marlonbrando alpacino jamescaan richards.castellano francisfordcoppola ',
 'early life career vito corleone new york portrayed son michael expands tightens grip family crime syndicate crime drama alpacino robertduvall dianekeaton robertdeniro francisfordcoppola ',
 'menace known joker emerges mysterious past wreaks havoc chaos people gotham dark knight must accept one greatest psychological physical tests ability fight injustice action crime drama christianbale heathledger aaroneckhart michaelcaine christophernolan ',
 'jury holdout attempts prevent miscarriage justice forcing colleagues reconsider evidence crime drama martinbalsam johnfiedler leej.cobb e.g.marshall sidneylumet ',
 'german occupied poland world wa

In [37]:
df['clean_input'] = l
df = df[['Title', 'clean_input']]
df.head()

Title                                        clean_input
0  The Shawshank Redemption  two imprisoned men bond number years finding s...
1             The Godfather  aging patriarch organized crime dynasty transf...
2    The Godfather: Part II  early life career vito corleone new york portr...
3           The Dark Knight  menace known joker emerges mysterious past wre...
4              12 Angry Men  jury holdout attempts prevent miscarriage just...

In [ ]:
## Feature Extraction


In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer  ## TF-ID Tools for converting text data into numerical formats
tfidf = TfidfVectorizer()
features = tfidf.fit_transform(df['clean_input'])

In [ ]:
## Cosine Similarity measure of similarity between two non-zero vectors(rows) defined in a feature matrix

In [40]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(features, features) ## It shows like the matrix(i,j)
print(cosine_sim)

[[1.         0.02693012 0.02567883 ... 0.00369409 0.00358765 0.00349224]
 [0.02693012 1.         0.18053579 ... 0.00386089 0.00374964 0.00364992]
 [0.02567883 0.18053579 1.         ... 0.00368149 0.00357542 0.00348033]
 ...
 [0.00369409 0.00386089 0.00368149 ... 1.         0.00373351 0.00363421]
 [0.00358765 0.00374964 0.00357542 ... 0.00373351 1.         0.0035295 ]
 [0.00349224 0.00364992 0.00348033 ... 0.00363421 0.0035295  1.        ]]


In [ ]:
## Movie Recommendation

In [41]:
index = pd.Series(df['Title'])
index.head()

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [42]:
def recommend_movies(title):
    movies = []
    idx = index[index == title].index[0]
    # print(idx)
    score = pd.Series(cosine_sim[idx]).sort_values(ascending=False)
    top10 = list(score.iloc[1:11].index)
    # print(top10)

    for i in top10:
        movies.append(df['Title'][i])
    return movies

In [43]:
recommend_movies('The Dark Knight Rises')


['The Dark Knight',
 'Inception',
 'Batman Begins',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Die Hard',
 'Sin City',
 'The Prestige',
 'Star Wars: Episode IV - A New Hope',
 'Mad Max: Fury Road',
 'Django Unchained']

In [44]:
index[index == 'The Dark Knight Rises'].index[0]


51

In [ ]:
## The below part of the code selects the fourth row (index 3) from the cosine similarity matrix and respresents the  cosine similarity scores of the fourth sample (row) with respect to all other samples in the feature matrix

In [45]:
pd.Series(cosine_sim[3]).sort_values(ascending=False)  ## It is arranged into a descending order


3      1.000000
51     0.193658
89     0.192066
40     0.126955
187    0.088099
         ...   
217    0.000000
150    0.000000
30     0.000000
145    0.000000
70     0.000000
Length: 250, dtype: float64

In [46]:
recommend_movies('The Shawshank Redemption')  ## It will shows the movies similar to 'The Shawshank Redemption'


['Pulp Fiction',
 'Se7en',
 'Rope',
 'Goodfellas',
 "Hachi: A Dog's Tale",
 'The Green Mile',
 'The Great Escape',
 'Million Dollar Baby',
 'Beauty and the Beast',
 'Unforgiven']

In [47]:
recommend_movies('The Avengers')


['Guardians of the Galaxy Vol. 2',
 'Aliens',
 'Guardians of the Galaxy',
 'The Martian',
 'Interstellar',
 'Blade Runner',
 'Kill Bill: Vol. 1',
 'The Thing',
 'Spider-Man: Homecoming',
 'The Terminator']